# Generated by Django 5.0.4 on 2024-04-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_card_alter_cards_identify_number'),
        ('users', '0002_alter_users_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='attendance.cards', verbose_name='Ключ-карта'),
        ),
    ]
