# Generated by Django 5.0.4 on 2024-04-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='group',
        ),
        migrations.AddField(
            model_name='users',
            name='is_notification_enabled',
            field=models.BooleanField(default=False, verbose_name='Включены ли уведомления по телеграму?'),
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
