# Generated by Django 5.0.4 on 2024-04-24 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_groups_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='self_group', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
    ]
