# Generated by Django 5.0.4 on 2024-05-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_groups_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Краткое наименование группы'),
        ),
    ]
