# Generated by Django 5.0.4 on 2024-04-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_card_alter_cards_identify_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='event_date',
        ),
    ]
