# Generated by Django 5.0.4 on 2024-05-01 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='attendance.cards', to_field='identify_number', verbose_name='Ключ-карта'),
        ),
    ]
