version: '3.3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.10
    env_file: ../web/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../web/
    env_file: ../web/.env
    volumes:
      - static:/app/static/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    depends_on:
      - backend
